
services:
  # خدمة قاعدة البيانات
  db:
    image: mysql:8.0
    container_name: restaurant_db_container
    restart: always
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db/restaurants.sql:/docker-entrypoint-initdb.d/restaurants.sql
      - mysql_data:/var/lib/mysql # لحفظ البيانات وضمان عدم ضياعها عند إيقاف الكونتينر

  # خدمة سيرفر الويب (التطبيق)
  web:
    build: .
    container_name: restaurant_app_container
    ports:
      - "8080:80"
    depends_on:
      - db

# تعريف المكان المخصص على الهاردسك لحفظ بيانات قاعدة البيانات بشكل دائم
volumes:
  mysql_data: